# .goreleaser.yml
# Build customization
version: 2
builds:
  - main: cmd/main.go
    binary: allhic
    hooks:
      pre: packr
      post: packr clean
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
